codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
      unit:
        target: auto
        threshold: 1%
        flags:
          - unit
      functional:
        target: auto
        threshold: 1%
        flags:
          - functional
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

flags:
  unit:
    paths:
      - src/
    carryforward: true
  functional:
    paths:
      - src/
    carryforward: true

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/__tests__/**"
  - "**/node_modules/**"
  - "coverage/**"
  - "scripts/**"
  - "util/**"

